#include "stdio.h"
#define INDEX 1000
#define MAX 42000

int main()
{
    unsigned int t,n,i,j,cnt,num=0,arr[INDEX+1]={0},tot=1;
    for(i=2;i<MAX;i++)
    {
        cnt=2;
        tot+=i;
        if(tot<1500000 || tot%10==0)
        {
            j=2;
            for(;j*j<=tot;j++)
            {
                if(tot%j==0)
                    cnt+=2;
            }
            if((--j)*j==tot)
                cnt--;
            if(cnt>INDEX)
                cnt=INDEX+1;
            for(j=cnt-1;j>0;j--)
            {
                if(arr[j])
                    break;
                arr[j]=tot;
                num++;
            }
            if(num==INDEX)
                break;
        }
    }
	scanf("%u",&t);
	for(i=0;i<t;i++)
	{
		scanf("%u",&n);
        printf("%u\n",arr[n]);
	}
	return 0;
}



// 162-167, 168-191, 192-239, 240-319, 320-479, 480-575, 576-647, 648-767, 768-1000
// 1385280, 1493856, 2031120, 2162160, 17907120, 76576500, 103672800, 236215980, 842161320

/*
 
The sequence of triangle numbers is generated by adding the natural numbers. So the 7'th triangle number would be 1+2+3+4+5+6+7=28. The first ten terms would be:
 
1,3,6,10,15,21,28,36,45,55,...
 
Let us list the factors of the first seven triangle numbers:
 
1: 1
3: 1,3
6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
 
We can see that 28 is the first triangle number to have over five divisors.
What is the value of the first triangle number to have over N divisors?
 
Input
First line T, the number of testcases. Each testcase consists of N in one line.
 
Output
For each testcase, print the required answer in one line.
 
Constraints
1<=T<=10
1<=N<=10^3
 
Sample input
4
1
2
3
4

Sample output
3
6
6
28
 
*/