#include "stdio.h"
#define RANGE 1000

unsigned long long seed;
void setSeed()
{
    seed = (seed ^ 25214903917L) & ((1L << 48) - 1);
}

int next(int bits)
{
    seed = (seed * 25214903917L + 11L) & ((1L << 48) - 1); //seed = (seed * multiplier + addend) mod (2 ^ 48)
    return (int) (seed >> (48 - bits));
}

int nextInt(int n)
{
//    if ((n & -n) == n) // i.e., n is a power of 2
//        return (int) ((n * (unsigned long long) next(31)) >> 31);
    int bits, val;
    do
    {
        bits = next(31);
        val = bits % n;
    } while (bits - val + (n - 1) < 0);
    return val;
}

int main()
{
    int t,i,cnt;
    unsigned long long j,n,m,ans;
    scanf("%d",&t);
    for(i=0;i<t;i++)
    {
        scanf("%llu %llu",&n,&m);
        unsigned long long arr[10];
        for(j=0;j<10;j++)
            scanf("%llu",&arr[j]);
        do
        {
            cnt=0;
            for(j=n;j<=m;j++)
            {
                seed=j;
                setSeed();
                if(nextInt(RANGE)==arr[0])
                {
                    cnt=1;
                    ans=j;
                    break;
                }
            }
            for(j=1;j<10;j++)
            {
                if(nextInt(RANGE)!=arr[j])
                {
                    n=ans+1;
                    break;
                }
                cnt++;
            }
        } while(cnt!=10);
        
        printf("%llu ",ans);
        for(j=0;j<9;j++)
            printf("%d ",nextInt(RANGE));
        printf("%d\n",nextInt(RANGE));
    }
	return 0;
}


/*

Task
Given a time range during which the Java Random generator was seeded and the last ten output values of random.nextInt(1000), guess the next value to be output by the generator.
 
Input Format
The first line of input contains a number N < 10 indicating the number of test cases to follow.
For each of the N test cases, a line will follow containing two space separated Unix timestamps representing the time during which the random number generator instance was created. The
range between the two timestamps will be, at most, 10^6.
The following ten lines contain the first ten numbers sequentially generated by the same Random instance's nextInt(1000) function, one on each line.
 
Output Format
For each test case, output a line containing the seed used to create the generator and the next 10 integers that are output from random.nextInt(1000), separated by spaces.
 
Sample Input
2
1374037200 1374123600
643
953
522
277
464
366
321
409
227
702
1374037299 1374143600
877
654
2
715
229
255
712
267
19
832
 
Sample Output
1374037200 877 633 491 596 839 875 923 461 27 826
1374037459 101 966 573 339 784 718 949 934 62 368

*/